### ISSUE TITLE
what does this error mean?

### ISSUE THREAD

**Issue by verbes4** [diafygi/letsencrypt-nosudo#107]
im a noob at this, i tried following the steps but once i get to the python part i get an error.
```
[verbpwfh@server299 letsencrypt-nosudo]$ python sign_csr.py --public-key user.pub domain.csr > signed.crt
Traceback (most recent call last):
  File "sign_csr.py", line 450, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "sign_csr.py", line 29, in sign_csr
    DIRECTORY = json.loads(urlopen(CA + "/directory").read().decode('utf8'))
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1205, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1172, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```
i have no idea what to do, all the previous steps ran fine but im getting this error now

**Comment by sepsamavi** [comment]
See: https://community.letsencrypt.org/t/https-acme-v01-api-letsencrypt-org-no-access/149619
