### ISSUE TITLE
Behind a load balancer the verification request fails

### ISSUE THREAD

**Issue by x89** [diafygi/letsencrypt-nosudo#45]
``` python
Press Enter when you've run the above commands in a new terminal window...
STEP 4: You need to run this command on domain.com (don't stop the python command until the next step).

sudo python -c "import BaseHTTPServer; \
    h = BaseHTTPServer.BaseHTTPRequestHandler; \
    h.do_GET = lambda r: r.send_response(200) or r.end_headers() or r.wfile.write('cu9iNGw0OyYzNJen0qLKhS8nXfYx9GRgt_YJZVfthZ8.mOKrxpIJxDEEW190JjtXbUZ385PCg0U_xpRJbQZCHq4'); \
    s = BaseHTTPServer.HTTPServer(('0.0.0.0', 80), h); \
    s.serve_forever()"

Press Enter when you've got the python command running on your server...
Requesting verification for domain.com...
Waiting for domain.com challenge to pass...
Traceback (most recent call last):
  File "sign_csr.py", line 441, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "sign_csr.py", line 372, in sign_csr
    raise KeyError("'{0}' challenge did not pass: {1}".format(i['domain'], challenge_status))
KeyError: "'domain.com' challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'domain.com/.well-known/acme-challenge/cu9iNGw0OyYzNJen0qLKhS8nXfYx9GRgt_YJZVfthZ8', u'hostname': u'domain.com', u'addressUsed': u'52.30.135.131', u'port': u'80', u'addressesResolved': [u'52.30.135.131', u'52.19.83.189']}], u'keyAuthorization': u'cu9iNGw0OyYzNJen0qLKhS8nXfYx9GRgt_YJZVfthZ8.mOKrxpIJxDEEW190JjtXbUZ385PCg0U_xpRJbQZCHq4', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/LFDuAzyge5nTj6Gn79vjIM4mrL0oGXxbAUCzJhiUjuc/1814396', u'token': u'cu9iNGw0OyYzNJen0qLKhS8nXfYx9GRgt_YJZVfthZ8', u'error': {u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://domain.com/.well-known/acme-challenge/cu9iNGw0OyYzNJen0qLKhS8nXfYx9GRgt_YJZVfthZ8 [52.30.135.131]: 503'}, u'type': u'http-01'}"
```

This is the error I get, you notice the IP addresses vary presumably because it's connecting to the load balancer which is sitting in front of the Python script listening on port 80.

Is there a way around that or do I have to temporarily mess with my DNS records in order to return a valid IP?

(PS. Not sure if this is the correct place to file this issue, perhaps the main letsencrypt repo would be better)

**Comment by x89** [comment]
I got around it by pointing the A records directly to an EC2 instance with the web app and running the required Python listeners from there, not sure that should have been required though!

**Comment by diafygi** [comment]
Glad you got it working. Since this app is not intended to run on your servers, it's up to you to figure out how to let requests come through.
