### ISSUE TITLE
Does not work in the wheezy hosts

### ISSUE THREAD

**Issue by zenny** [diafygi/letsencrypt-nosudo#57]
Thanks for the very useful script.

Redirected from https://gist.github.com/kennwhite/aa74c164bcdf092a7a10. Tried on Debian Wheezy host.

Everything went alright except at STEP 4 running in the webserver.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

```

Tried to revoke without success.

```
$ python revoke_crt.py --public-key user.pub domain.crt'
Reading pubkey file...
Found public key!
...
Traceback (most recent call last):
  File "revoke_crt.py", line 136, in <module>
    revoke_crt(args.public_key, args.crt_path)
  File "revoke_crt.py", line 97, in revoke_crt
    resp = urllib2.urlopen("{0}/acme/revoke-cert".format(CA), crt_data)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

```

**Comment by 0rovan** [comment]
Turn your web server (or whatever is occupying port 80) off while running step 4.

**Comment by diafygi** [comment]
Correct, or use the `--file-based` option and manually put the verification file in the correct folder on your webserver.
