### ISSUE TITLE
agreement url changed

### ISSUE THREAD

**Issue by vayw** [diafygi/letsencrypt-nosudo#80]
Agreement url changed since August 1th, so probably it need to be updated in code.
Got this error last time, which is gone after i update url in sign_csr.py

```
Error: reg_data:
POST https://acme-v01.api.letsencrypt.org/acme/new-reg
{
    "header": {
        "alg": "RS256", 
        "jwk": {
            "e": "AQAB", 
            "kty": "RSA", 
            "n": "REMOVED"
}
{
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]",
  "status": 400
}
Traceback (most recent call last):
  File "../letsencrypt-nosudo/sign_csr.py", line 446, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "../letsencrypt-nosudo/sign_csr.py", line 198, in sign_csr
    resp = urllib2.urlopen(reg_url, reg_data)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
```

**Comment by diafygi** [comment]
Thanks! Should be fixed in 8749f651907729d09cfbd1f0e54481a5b7b59036
